import type { Metadata } from "next";
import "./globals.css";
import { Poppins, Bricolage_Grotesque, Inter, Space_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import VibeRefreshReminder from "./components/VibeRefreshReminder";
import AppLayout from "./components/AppLayout";

const poppins = Poppins({
  subsets: ["latin"],
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
  ],
  display: "swap",
});

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
  variable: "--font-bricolage",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
  display: "swap",
});

const spaceMono = Space_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-space-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${bricolage.variable} ${inter.variable} ${spaceMono.variable} antialiased`}>
        <AppLayout>{children}</AppLayout>
        <Toaster/>
        <VibeRefreshReminder />
      </body>
    </html>
  );
}
